services:
- type: web
  name: fastapi-starter
  env: docker
  plan: free
  docker:
    image: ghcr.io/haris294/fastapi-starter:latest
  healthCheckPath: /ready
  autoDeploy: true
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: fastapi-db
      property: internalConnectionString
  # Optional: set REDIS_URL if you have Upstash/Render Redis later.
  # - key: REDIS_URL
  #   value: <your-redis-url>

databases:
- name: fastapi-db
  plan: free
