services:
- type: web
  name: fastapi-starter
  env: docker
  plan: free
  docker:
    image: ghcr.io/haris294/fastapi-starter:latest
  healthCheckPath: /health
  autoDeploy: true
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: fastapi-db
      property: internalConnectionString

databases:
- name: fastapi-db
  plan: free
